// Code generated by hertz generator.

package main

import (
	"music-backEnd/biz/dal"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
)

func main() {
	dal.Init()
	h := server.New(
		server.WithMaxRequestBodySize(4*1024*1024*1024),
		server.WithStreamBody(true),
	)

	h.Use(cors.Default())

	register(h)
	h.Spin()
}
